### ISSUE TITLE
通学路のグリーンベルト表示の道を赤色から緑色に変更

### ISSUE THREAD

**Issue by taisukef** [code4fukui/kunitaka-map#14]
https://github.com/code4fukui/kunitaka/issues/12
から転記

**Comment by jarikoro** [comment]
表示選択を付けなおすとグリーベルトの表示が消えてしまいます
グリーベルトの位置は正しいことを確認しました

**Comment by taisukef** [comment]
対応、完了！

**Comment by jarikoro** [comment]
確認しました
ありがとうございます
インター生は苦労してましたー
